name: club-registration

services:
  mysql:
    image: mysql:8.0
    container_name: club_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: club_user
      MYSQL_PASSWORD: club_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - club_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: club_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: club_user
      PMA_PASSWORD: club_password
    depends_on:
      - mysql
    networks:
      - club_network

  web:
    build: .
    container_name: club_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./src/php:/var/www/html/php
      - ./assets:/var/www/html/assets
    depends_on:
      - mysql
    networks:
      - club_network

volumes:
  mysql_data:

networks:
  club_network:
    driver: bridge

# # ดูสถานะ containers
# docker compose ps

# # ดู logs ของ container
# docker compose logs [service_name]

# # หยุด services
# docker compose down

# # เริ่มต้น services ใหม่
# docker compose up -d

# # เริ่มต้น services พร้อม build ใหม่
# docker compose up --build -d

# http://localhost/index.html  
# http://localhost/admin.html 